package entidades;
// Generated Aug 8, 2018 3:30:00 PM by Hibernate Tools 4.3.1



/**
 * AuthorReference generated by hbm2java
 */
public class AuthorReference  implements java.io.Serializable {


     private int id;
     private Author author;
     private Link link;

    public AuthorReference() {
    }

	
    public AuthorReference(int id) {
        this.id = id;
    }
    public AuthorReference(int id, Author author, Link link) {
       this.id = id;
       this.author = author;
       this.link = link;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
    public Link getLink() {
        return this.link;
    }
    
    public void setLink(Link link) {
        this.link = link;
    }




}


