package entidades;
// Generated Aug 8, 2018 3:30:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private int id;
     private String name;
     private String biography;
     private Set authorReferences = new HashSet(0);

    public Author() {
    }

	
    public Author(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Author(int id, String name, String biography, Set authorReferences) {
       this.id = id;
       this.name = name;
       this.biography = biography;
       this.authorReferences = authorReferences;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBiography() {
        return this.biography;
    }
    
    public void setBiography(String biography) {
        this.biography = biography;
    }
    public Set getAuthorReferences() {
        return this.authorReferences;
    }
    
    public void setAuthorReferences(Set authorReferences) {
        this.authorReferences = authorReferences;
    }




}


