package entidades;
// Generated Aug 8, 2018 3:30:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Link generated by hbm2java
 */
public class Link  implements java.io.Serializable {


     private int id;
     private Category category;
     private String title;
     private String description;
     private String link;
     private Set authorReferences = new HashSet(0);

    public Link() {
    }

	
    public Link(int id, Category category, String title, String description, String link) {
        this.id = id;
        this.category = category;
        this.title = title;
        this.description = description;
        this.link = link;
    }
    public Link(int id, Category category, String title, String description, String link, Set authorReferences) {
       this.id = id;
       this.category = category;
       this.title = title;
       this.description = description;
       this.link = link;
       this.authorReferences = authorReferences;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Set getAuthorReferences() {
        return this.authorReferences;
    }
    
    public void setAuthorReferences(Set authorReferences) {
        this.authorReferences = authorReferences;
    }




}


